In [2]:
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [3]:
clf = GaussianNB()
clf.fit(np.asarray([[1, 2, 3], [1, 3, 2], [3, 3, 1], [3, 3, 2], [100, 100, -39812]]), np.asarray([1, 1, 0, 0, 2]))
clf.predict_proba(np.asarray([[1, 1, 3], [1, 4, 1], [5, 5, 5], [1, 12313, -12312]]))

array([[2.55474280e-07, 9.99999745e-01, 0.00000000e+00],
       [4.99314631e-03, 9.95006854e-01, 0.00000000e+00],
       [9.99999922e-01, 7.83154499e-08, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [51]:
x = np.array([
    [2, 3], # x1
    [0, 1], # x2
    [4, 1], # x3
    [22, 1] # x4
])

np.max(x, axis=-1).reshape(-1), np.argmax(x, axis=-1).reshape(-1)

(array([ 3,  1,  4, 22]), array([1, 1, 0, 0], dtype=int64))

In [48]:
np.max(x[:,:,1], axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [29]:
xx = np.array([[1, 2], [0, 0]])
xx[0] += np.array([2, 1])
xx

array([[3, 3],
       [0, 0]])